apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: api-trash-hpa
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: api-trash
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 80
