apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: api-authentication
  name: api-authentication
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-authentication
  template:
    metadata:
      labels:
        app: api-authentication
    spec:
      containers:
      - image: europe-west9-docker.pkg.dev/j-irais-bruler-chez-vous/api-authentication/production
        name: api-authentication
        env:
          - name: DB_HOST
            value: "10.83.80.3"
          - name: DB_PORT
            value: "5432"
          - name: DB_USER
            value: "postgres"
          - name: DB_PASSWORD
            value: "postgres"
          - name: DB_NAME
            value: "db_auth"
          - name: TCP_AUTHENTICATION_HOST
            value: "api-authentication"
          - name: TCP_MESSAGE_HOST
            value: "api-message"
          - name: TCP_USER_HOST
            value: "api-user"
          - name: TCP_TRASH_HOST
            value: "api-trash"
          - name: JWT_SECRET
            value: "Hc5f4g@5h6j7k8lqs9a2s3de4f&&5g6hed7j8k9l"
        ports:
          - containerPort: 3000

---
apiVersion: "autoscaling/v2"
kind: "HorizontalPodAutoscaler"
metadata:
  name: "api-authentication-hpa"
  namespace: "default"
  labels:
    app: "api-authentication"
spec:
  scaleTargetRef:
    kind: "Deployment"
    name: "api-authentication"
    apiVersion: "apps/v1beta1"
  minReplicas: 1
  maxReplicas: 5
  metrics:
    - type: "Resource"
      resource:
        name: "cpu"
        target:
          type: "Utilization"
          averageUtilization: 80

