apiVersion: v1
kind: Service
metadata:
  labels:
    app: api-authentication
  name: api-authentication
spec:
  ports:
  - name: "3000"
    port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: api-authentication
  type: ClusterIP
