apiVersion: v1
kind: Service
metadata:
  labels:
    app: api-user
  name: api-user
spec:
  ports:
  - name: "3001"
    port: 3001
    protocol: TCP
    targetPort: 3001
  selector:
    app: api-user
  type: ClusterIP
