apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: front-web
  name: front-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: front-web
  template:
    metadata:
      labels:
        app: front-web
    spec:
      containers:
      - image: europe-west9-docker.pkg.dev/j-irais-bruler-chez-vous/front-web/production
        name: front-web
        env:
          - name: JWT_SECRET
            value: "Hc5f4g@5h6j7k8lqs9a2s3de4f&&5g6hed7j8k9l"
        ports:
          - containerPort: 3000
