apiVersion: v1
kind: Service
metadata:
  labels:
    app: front-web
  name: front-web-internal
spec:
  ports:
  - name: "80"
    port: 80
    protocol: TCP
    targetPort: 3000
  selector:
    app: front-web
  type: ClusterIP
