apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: api-mailing
  name: api-mailing
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-mailing
  template:
    metadata:
      labels:
        app: api-mailing
    spec:
      containers:
      - image: europe-west9-docker.pkg.dev/j-irais-bruler-chez-vous/api-mailing/production
        name: api-mailing
        env:
          - name: DB_HOST
            value: "10.83.80.3"
          - name: DB_PORT
            value: "5432"
          - name: DB_USER
            value: "postgres"
          - name: DB_PASSWORD
            value: "postgres"
          - name: DB_NAME
            value: "db_mailing"
          - name: TCP_AUTHENTICATION_HOST
            value: "api-authentication"
          - name: TCP_MESSAGE_HOST
            value: "api-message"
          - name: TCP_USER_HOST
            value: "api-user"
          - name: TCP_TRASH_HOST
            value: "api-trash"
          - name: TCP_MANIFESTATION_HOST
            value: "api-manifestation"
          - name: TCP_MAILING_HOST
            value: "api-mailing"
          - name: JWT_SECRET
            value: "Hc5f4g@5h6j7k8lqs9a2s3de4f&&5g6hed7j8k9l"
          - name: RESEND_API_KEY
            value: "re_fmFXoY9y_Q494jmsbFPu7e7FD4g74TmG3"
          - name: RABBITMQ_URL
            value : "amqp://default_user_-dJ2qIsoBl-7n4EbQgs:j8m0p5SBoKX2Ua0HDqNVB2SBQeaSjuIh@hello-world:5672"
        ports:
          - containerPort: 5672

---
apiVersion: "autoscaling/v2"
kind: "HorizontalPodAutoscaler"
metadata:
  name: "api-mailing-hpa"
  namespace: "default"
  labels:
    app: "api-mailing"
spec:
  scaleTargetRef:
    kind: "Deployment"
    name: "api-mailing"
    apiVersion: "apps/v1"
  minReplicas: 1
  maxReplicas: 5
  metrics:
    - type: "Resource"
      resource:
        name: "cpu"
        target:
          type: "Utilization"
          averageUtilization: 80
