apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: api-gateway
  name: api-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
      - image: europe-west9-docker.pkg.dev/j-irais-bruler-chez-vous/api-gateway/production
        name: api-gateway
        env:
          - name: JWT_SECRET
            value: "Hc5f4g@5h6j7k8lqs9a2s3de4f&&5g6hed7j8k9l"
          - name: TCP_AUTHENTICATION_HOST
            value: "api-authentication"
          - name: TCP_MESSAGE_HOST
            value: "api-message"
          - name: TCP_USER_HOST
            value: "api-user"
          - name: TCP_TRASH_HOST
            value: "api-trash"
          - name: TCP_MANIFESTATION_HOST
            value: "api-manifestation"
          - name: FRONTEND_URL
            value: "https://j-irais-bruler-chez-vous.com"
        ports:
          - containerPort: 3333

---
apiVersion: "autoscaling/v2"
kind: "HorizontalPodAutoscaler"
metadata:
  name: "api-gateway-hpa"
  namespace: "default"
  labels:
    app: "api-gateway"
spec:
  scaleTargetRef:
    kind: "Deployment"
    name: "api-gateway"
    apiVersion: "apps/v1"
  minReplicas: 1
  maxReplicas: 5
  metrics:
    - type: "Resource"
      resource:
        name: "cpu"
        target:
          type: "Utilization"
          averageUtilization: 80
