apiVersion: v1
kind: Service
metadata:
  labels:
    app: api-gateway
  name: api-gateway-external
spec:
  ports:
  - name: "80"
    port: 80
    protocol: TCP
    targetPort: 3333
  - name: "9001"
    port: 9001
    protocol: TCP
    targetPort: 9001
  selector:
    app: api-gateway
  type: LoadBalancer
