apiVersion: v1
kind: Service
metadata:
  labels:
    app: api-gateway
  name: api-gateway
spec:
  ports:
  - name: "80"
    port: 80
    protocol: TCP
    targetPort: 3333
  selector:
    app: api-gateway
  type: NodePort
