apiVersion: v1
kind: Service
metadata:
  labels:
    app: api-manifestation
  name: api-manifestation
spec:
  ports:
  - name: "3003"
    port: 3003
    protocol: TCP
    targetPort: 3003
  selector:
    app: api-manifestation
  type: ClusterIP
