apiVersion: v1
kind: Service
metadata:
  labels:
    app: api-manifestation
  name: api-manifestation
spec:
  ports:
  - name: "3004"
    port: 3004
    protocol: TCP
    targetPort: 3004
  selector:
    app: api-manifestation
  type: ClusterIP
